'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { commerceFetch } from '../../../lib/commerce';
type Settings = { contactPhone: string; messengerUrl: string; defaultShippingFeeVnd: number | null };
export default function AdminStoreSettings() {
  const router=useRouter(); const [settings,setSettings]=useState<Settings|null>(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;void commerceFetch('/api/v1/admin/settings').then(async response=>{if(response.status===401){router.replace('/admin/login');return;}if(response.ok){const body=await response.json();if(active)setSettings(body.data);}else if(active)setMessage('Không tải được cài đặt.');}).catch(()=>active&&setMessage('Không thể kết nối máy chủ.'));return()=>{active=false}},[router]);
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const raw=String(f.get('fee')??'').trim();setBusy(true);setMessage('');try{const r=await commerceFetch('/api/v1/admin/settings',{method:'PATCH',body:JSON.stringify({contactPhone:f.get('phone'),messengerUrl:f.get('messenger'),defaultShippingFeeVnd:raw===''?null:Number(raw)})});if(!r.ok)setMessage((await r.json()).error?.message??'Không lưu được cài đặt.');else{setSettings((await r.json()).data);setMessage('Đã lưu cài đặt cửa hàng.');}}catch{setMessage('Không thể kết nối máy chủ.');}finally{setBusy(false)}}
  return <section className="admin-content"><div className="admin-page-heading"><div><p className="eyebrow">QUẢN LÝ CỬA HÀNG</p><h1>Cài đặt cửa hàng</h1></div></div>{message&&<p className="admin-message" role="status">{message}</p>}<article className="admin-card"><form className="admin-settings-form settings-single" onSubmit={save}>{settings&&<><label>Số điện thoại<input name="phone" type="tel" defaultValue={settings.contactPhone} maxLength={24} required/></label><label>Liên kết Messenger<input name="messenger" type="url" defaultValue={settings.messengerUrl} maxLength={300} required/></label><label>Phí giao hàng mặc định (₫)<input name="fee" type="number" min="0" max="2000000" step="1" defaultValue={settings.defaultShippingFeeVnd??''} placeholder="Để trống nếu chưa cấu hình"/></label><button className="commerce-primary" disabled={busy}>Lưu cài đặt</button></>}</form></article></section>;
}
