'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { commerceFetch } from '../../../lib/commerce';
type Product = { id: string; slug: string; name: string; basePriceVnd: number; discountPercent: number; isActive: boolean };
type Settings = { contactPhone: string; messengerUrl: string; defaultShippingFeeVnd: number | null };
export default function AdminProductsSettings() {
  const router=useRouter();const [products,setProducts]=useState<Product[]>([]);const [settings,setSettings]=useState<Settings|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{let live=true;void Promise.all([commerceFetch('/api/v1/admin/products'),commerceFetch('/api/v1/admin/settings')]).then(async([p,s])=>{if(p.status===401||s.status===401){router.replace('/admin/login');return}const [pd,sd]=await Promise.all([p.json(),s.json()]);if(live&&p.ok&&s.ok){setProducts(pd.data);setSettings(sd.data)}else if(live)setMessage('Không tải được cài đặt quản trị.')} ).catch(()=>live&&setMessage('Không thể kết nối máy chủ.'));return()=>{live=false}},[router]);
  async function saveProduct(event:React.FormEvent<HTMLFormElement>,product:Product){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setMessage('');try{const response=await commerceFetch(`/api/v1/admin/products/${product.id}`,{method:'PATCH',body:JSON.stringify({basePriceVnd:Number(form.get('price')),discountPercent:Number(form.get('discount')),isActive:form.get('active')==='on'})});if(!response.ok)setMessage((await response.json()).error?.message??'Không lưu được sản phẩm.');else{setProducts((all)=>all.map((item)=>item.id===product.id?{...item,basePriceVnd:Number(form.get('price')),discountPercent:Number(form.get('discount')),isActive:form.get('active')==='on'}:item));setMessage(`Đã lưu ${product.name}.`)}}catch{setMessage('Không thể kết nối máy chủ.')}finally{setBusy(false)}}
  async function saveSettings(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!settings)return;const form=new FormData(event.currentTarget);setBusy(true);setMessage('');const fee=String(form.get('fee')??'').trim();try{const response=await commerceFetch('/api/v1/admin/settings',{method:'PATCH',body:JSON.stringify({contactPhone:form.get('phone'),messengerUrl:form.get('messenger'),defaultShippingFeeVnd:fee===''?null:Number(fee)})});if(!response.ok)setMessage((await response.json()).error?.message??'Không lưu được cài đặt.');else{setSettings((await response.json()).data);setMessage('Đã lưu cài đặt cửa hàng.')}}catch{setMessage('Không thể kết nối máy chủ.')}finally{setBusy(false)}}
  return <section className="admin-content"><div className="admin-page-heading"><div><p className="eyebrow">QUẢN LÝ CỬA HÀNG</p><h1>Sản phẩm & cài đặt</h1></div></div>{message&&<p className="admin-message" role="status">{message}</p>}<article className="admin-card"><h2>Thông tin cửa hàng</h2><form className="admin-settings-form" onSubmit={saveSettings}>{settings&&<><label>Số điện thoại<input name="phone" type="tel" defaultValue={settings.contactPhone} maxLength={24} required/></label><label>Liên kết Messenger<input name="messenger" type="url" defaultValue={settings.messengerUrl} maxLength={300} required/></label><label>Phí giao hàng mặc định (₫)<input name="fee" type="number" min="0" max="2000000" step="1" defaultValue={settings.defaultShippingFeeVnd??''} placeholder="Để trống nếu chưa cấu hình"/></label><button className="commerce-primary" disabled={busy}>Lưu cài đặt</button></>}</form></article><div className="admin-section-heading"><h2>Sản phẩm</h2><p>Giá biến thể dùng giá riêng nếu có; nếu không sẽ dùng giá cơ bản.</p></div><div className="admin-product-list">{products.map((product)=><form className="admin-card admin-product-form" key={product.id} onSubmit={(event)=>void saveProduct(event,product)}><div><b>{product.name}</b><small>{product.slug}</small></div><label>Giá cơ bản<input name="price" type="number" min="0" max="2000000000" step="1" defaultValue={product.basePriceVnd} required/></label><label>Giảm giá (%)<input name="discount" type="number" min="0" max="100" step="1" defaultValue={product.discountPercent} required/></label><label className="admin-checkbox"><input name="active" type="checkbox" defaultChecked={product.isActive}/> Đang bán</label><button className="commerce-primary" disabled={busy}>Lưu</button></form>)}</div></section>;
}
