'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { commerceFetch, formatMoney } from '../../../../lib/commerce';
type Detail = { id: string; orderCode: string; customerName: string; customerPhone: string; deliveryAddress: string; note: string; status: string; subtotalVnd: number; shippingFeeVnd: number; totalVnd: number; items: { productName: string; sku: string; colorName: string; size: string; originalPriceVnd: number; discountPercent: number; salePriceVnd: number; quantity: number; lineTotalVnd: number }[] };
export default function AdminOrderDetail({ orderId }: { orderId: string }) {
  const router = useRouter(); const [data,setData]=useState<Detail|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function load(){const response=await commerceFetch(`/api/v1/admin/orders/${orderId}`);if(response.status===401){router.replace('/admin/login');return}const payload=await response.json();if(response.ok)setData(payload.data);else setError(payload.error?.message??'Không tải được đơn hàng.');}
  useEffect(()=>{let active=true;void commerceFetch(`/api/v1/admin/orders/${orderId}`).then(async(response)=>{if(response.status===401){router.replace('/admin/login');return}const payload=await response.json();if(active&&response.ok)setData(payload.data);else if(active)setError(payload.error?.message??'Không tải được đơn hàng.')}).catch(()=>{if(active)setError('Không thể kết nối máy chủ.')});return()=>{active=false}},[orderId,router]);
  async function update(status:string){setBusy(true);setError('');try{const response=await commerceFetch(`/api/v1/admin/orders/${orderId}/status`,{method:'PATCH',body:JSON.stringify({status})});if(!response.ok)setError((await response.json()).error?.message??'Không thể cập nhật trạng thái.');else await load()}catch{setError('Không thể kết nối máy chủ.')}finally{setBusy(false)}}
  if(!data)return <section className="admin-content"><button className="text-action" onClick={()=>router.back()}>← Quay lại</button>{error&&<p className="commerce-error">{error}</p>}</section>;
  const actions:Record<string,string[]>={NEW:['CONFIRMED','CANCELLED'],CONFIRMED:['SHIPPING','CANCELLED'],SHIPPING:['COMPLETED'],COMPLETED:[],CANCELLED:[]};
  return <section className="admin-content"><button className="text-action" onClick={()=>router.push('/admin/orders')}>← Danh sách đơn hàng</button><div className="admin-page-heading"><div><p className="eyebrow">CHI TIẾT ĐƠN</p><h1>{data.orderCode}</h1></div><span className="order-status">{data.status}</span></div>{error&&<p className="commerce-error">{error}</p>}<div className="admin-detail-grid"><article className="admin-card"><h2>Thông tin nhận hàng</h2><p><b>{data.customerName}</b></p><p><a href={`tel:${data.customerPhone}`}>{data.customerPhone}</a></p><p>{data.deliveryAddress}</p>{data.note&&<p>Ghi chú: {data.note}</p>}</article><article className="admin-card"><h2>Tổng đơn hàng</h2><p>Tạm tính <b>{formatMoney(Number(data.subtotalVnd))}</b></p><p>Phí giao hàng <b>{formatMoney(Number(data.shippingFeeVnd))}</b></p><p className="admin-total">Tổng cộng <b>{formatMoney(Number(data.totalVnd))}</b></p></article></div><article className="admin-card"><h2>Sản phẩm</h2>{data.items.map((item,index)=><div className="admin-order-item" key={`${item.sku}-${index}`}><div><b>{item.productName}</b><p>{item.colorName} · {item.size} · {item.sku}</p><p>{formatMoney(Number(item.salePriceVnd))}{Number(item.discountPercent)>0&&<small> (giảm {item.discountPercent}%)</small>} × {item.quantity}</p></div><b>{formatMoney(Number(item.lineTotalVnd))}</b></div>)}</article><div className="admin-actions">{actions[data.status]?.map((status)=><button key={status} disabled={busy} className={status==='CANCELLED'?'admin-danger':'commerce-primary'} onClick={()=>void update(status)}>{status==='CONFIRMED'?'Xác nhận':status==='SHIPPING'?'Đánh dấu đang giao':status==='COMPLETED'?'Hoàn tất':'Hủy đơn'}</button>)}</div></section>;
}
